language: ruby
rvm:
  - jruby-19mode

install:
  - bundle install

script:
  - rake assets:precompile
  - bundle exec warble war

after_success:
   - echo "<settings><servers><server><id>snapshots</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server><server><id>release</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>" > ~/settings.xml
   - "[[ $TRAVIS_PULL_REQUEST == false ]] && ./deploy.sh"